initial_enable: false

livox_roi:
  uav_radius: 0.3
  max_coord: 20.0
  debug_level: 0

voxel:
  leaf_size: 0.05

map:
  decay_coeff: 0.1
  ini_intensity: 50

register:
  max_correspondence_distance: 0.5
  max_iter: 50
  transformation_epsilon: 1e-8
  euclidean_fitness_epsilon: 0.001

roi:
  uav_radius: 0.3
  x_min: -0.5
  x_max: 4.5
  y_min: -7.0
  y_max: 1.0
  z_min: 0.3
  z_max: 2.0

dilation:
  radius: 0.25
  steps: 12

erosion:
  mean_k: 6 #越大过滤越狠
  thresh: 1.5 #越小过滤越狠

projection:
  plane_z: 0.7